version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: devices-db
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: devices_user
      POSTGRES_PASSWORD: devices_pass
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices_user -d devicesdb"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped
    networks:
      device-api-postgres:

  app:
    build: .
    container_name: devices-api
    depends_on:
        db:
          condition: service_healthy
    ports:
        - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://devices-db:5432/devicesdb
      SPRING_DATASOURCE_USERNAME: devices_user
      SPRING_DATASOURCE_PASSWORD: devices_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SERVER_PORT: 8080
    networks:
      device-api-postgres:



volumes:
  db_data:

networks:
  device-api-postgres:
     driver: bridge
