version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: devices-db
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: devices_user
      POSTGRES_PASSWORD: devices_pass
    ports:
      - "5434:5432"          # host:container
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devices_user -d devicesdb" ]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql:
    image: mysql:8.4
    container_name: devices-mysql
    environment:
      MYSQL_DATABASE: devicesdb
      MYSQL_USER: devices_user
      MYSQL_PASSWORD: devices_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_v2:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD --silent" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  app:
    build: .
    container_name: devices-api-mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8085:8085"        # host:container
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devicesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: devices_user
      SPRING_DATASOURCE_PASSWORD: devices_pass
      # Key line: let Hibernate manage the schema
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Optional (handy for debugging)
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SERVER_PORT: 8085
    restart: unless-stopped

volumes:
  mysql_data_v2:
  db_data:
