spring:
  application:
    name: devices-api

  datasource:
    url: jdbc:mysql://localhost:3307/devicesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: devices_user
    password: devices_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # optional but nice to force:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8085
