spring:
  application:
    name: devices-api

  datasource:
    url: jdbc:postgresql://localhost:5432/devicesdb
    username: devices_user
    password: devices_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8085
